services:
  dashboard:
    image: grafana/grafana:7.4.0
    container_name: jccic-dashboard
    ports:
      - 3000:3000
    #volumes:
    #  - grafana-data:/var/lib/grafana

  tsdb:
    build: ./tsdb
    container_name: metrics-db
    ports:
      - 8086:8086
    #volumes:
    #  - influxdb-data:/root/.influxdbv2

  db:
    image: postgres:13
    restart: always
    container_name: events-db
    environment:
      POSTGRES_PASSWORD: ccicevents
    volumes:
      - ./db/db-scripts:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

  adminer:
    image: adminer:4.7.9
    restart: always
    ports:
      - 4000:8080


#volumes:
#  grafana-data:
#    external: true
#  influxdb-data:
#    external: true