version: '3'

services:
  dashboard:
    image: grafana/grafana:7.4.0
    container_name: dashboard
    restart: always
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
      - ./dashboard/provisioning/:/etc/grafana/provisioning/
      - ./dashboard/horus_dashboard.ini:/etc/grafana/horus_dashboard.ini
      - ./dashboard/cert.pem:/etc/grafana/cert.pem
      - ./dashboard/key.pem:/etc/grafana/key.pem
    env_file:
      - ./dashboard/dashboard.env
    depends_on:
      - tsdb
      - db


  tsdb:
    build: ./tsdb
    restart: always
    container_name: metrics-db
    ports:
      - 8086:8086
    volumes:
      - ./tsdb/config.yml:/config.yml

  db:
    image: postgres:12
    restart: always
    container_name: events-db
    environment:
      POSTGRES_PASSWORD: ccicevents
    volumes:
      - ./db/db-scripts:/docker-entrypoint-initdb.d

  adminer:
    image: adminer:4.7.9
    container_name: adminer-aux
    restart: always
    ports:
      - 4000:8080

  horus-api:
    build: ./api
    container_name: api-horus
    restart: always
    ports:
      - 443:443
      - 80:80
    env_file:
      - api/horus-api.env
    depends_on:
      - tsdb
      - db

networks:
  default:
    external:
      name: horus-ccic

volumes:
  grafana-data:
   external: true
