services:
  dashboard:
    image: grafana/grafana:7.4.0
    container_name: dashboard
    restart: always
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana

  tsdb:
    build: ./tsdb
    restart: always
    container_name: metrics-db
    volumes:
      - ./tsdb/config.yml:/config.yml

  db:
    image: postgres:13
    restart: always
    container_name: events-db
    environment:
      POSTGRES_PASSWORD: ccicevents
    volumes:
      - ./db/db-scripts:/docker-entrypoint-initdb.d

  adminer:
    image: adminer:4.7.9
    container_name: adminer-aux
    restart: always
    ports:
      - 4000:8080

  horus-api:
    build: ./api
    container_name: api-horus
    restart: always
    ports:
      - 8080:5000
    env_file:
      - horus-api.env



volumes:
  grafana-data:
   external: true
