{
 "title": "CCIC - Comunicaciones",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Inicio", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
   "options": {
    "content": "## CCIC\n---\n![DGCI](https://cominfo.ejercito.mil.ar/Imagenes/EscudoHeraldica.jpg) \n         "
   },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Hora Actual",
   "type": "grafana-clock-panel",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "targets": [
    {}
   ]
  },
  { "title": "Logística", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Combustible Generadores",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "FinalOutput = [\"_value\", \"_time\", \"_measurement\", \"generador\"]\r\n\r\ndata = from(bucket: \"combustible-generador\")\r\n  |> range(start: -5m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"litros\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"nivel\")\r\n  |> aggregateWindow(every: 5m, fn: last)\r\n  |> unique(column: \"generador\")\r\n\r\nrenamedData = data\r\n    |> map(fn: (r) => ({_value:r._value, _time:r._time, _measurement:\"Litros\",_field:\"Nivel\", generador:r.generador}))\r\n    |> keep(columns:FinalOutput)\r\n\r\nrenamedData |> yield()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Tensión Generadores",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "data = from(bucket: \"alimentacion-electrica\")\r\n  |> range(start: -5m, stop: now())\r\n  |> aggregateWindow(every: 1m, fn: median, createEmpty: false)\r\n  |> unique(column: \"generador\")\r\n\r\nrenamedData = data\r\n  |> map(fn: (r) => ({_field:\"Tension\" , generador:r.generador, _value:r._value, _measurement:r._measurement, _time:r._time}))\r\n\r\n\r\nrenamedData |> yield()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Comunicaciones", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Cola CMD",
   "type": "graph",
   "description": "Cantidad de mensajes en espera en la bandeja de entrada del Centro de Mensajes Digital",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "MM", "label": "Mensajes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "FinalOutput = [\"_value\", \"_time\", \"_field\", \"facilidad\"]\r\n\r\ndata = from(bucket: \"colas-espera\")\r\n  |> range(start: -1h, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"long_cola\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"long_cola\")\r\n  |> filter(fn: (r) => r[\"facilidad\"] == \"Centro de Mensajes\")\r\n  |> aggregateWindow(every: 1m, fn: last, createEmpty: false)\r\n\r\nrenamedData = data\r\n    |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"Longitud Cola MM\", facilidad:r.facilidad}))\r\n    |> keep(columns:FinalOutput)\r\n\r\nrenamedData |> yield()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cola de MM de Facilidades",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "FinalOutput = [\"_value\", \"_time\", \"_field\", \"facilidad\"]\r\n\r\ndata = from(bucket: \"colas-espera\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"long_cola\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"long_cola\")\r\n  |> filter(fn: (r) => r[\"facilidad\"] == \"Red Cdo\" or r[\"facilidad\"] == \"Red Cdo Op\" or r[\"facilidad\"] == \"Red Icia\" or r[\"facilidad\"] == \"Red Mat Pers\" or r[\"facilidad\"] == \"Red Op\")\r\n\r\nrenamedData = data\r\n    |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"Longitud Cola MM\", facilidad:r.facilidad}))\r\n    |> keep(columns:FinalOutput)\r\n\r\nrenamedData |> yield()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Estado de Servicio",
   "type": "table",
   "description": "Ultimo horario y estado reportado por la facilidad. Tener en cuenta no solo el estado si no su ausencia.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 29 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "FinalOutput = [\"Estado\", \"Ultima Actualización\",  \"Facilidad\"]\r\n\r\ndata = from(bucket: \"estado-servicio\")\r\n  |> range(start: -5m)\r\n  |> last()\r\n  |> group()\r\n  |> keep(columns: [\"_time\", \"_value\", \"facilidad\"])\r\n  |> unique(column: \"facilidad\")\r\n\r\nrenamedData = data\r\n  |> map(fn: (r) => ({\"Estado\":r._value, \"Ultima Actualización\":r._time, \"Facilidad\":r.facilidad}))\r\n  |> keep(columns:FinalOutput)\r\n\r\nrenamedData |> yield()\r\n\r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Procesamiento de MM",
   "type": "table",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 29 },
   "targets": [
    {
     "rawSql": "select \n\tnro_mm as \"Nro MM\", \n\tclasif_seg as \"Clasificacion\", \n\tprecedencia as \"Precedencia\",\n\tarray_to_string(array(select distinct unnest(array_agg(origen) || array_agg(destino))), ' - ') as \"Facilidades\" ,\n\tage(max(gfh),min(gfh)) as \"Tiempo Diligenciamiento\"\nfrom public.mm_events \ngroup by nro_mm, clasif_seg, precedencia\norder by nro_mm;"
    }
   ]
  }
 ]
}